In [69]:
# Importing required lib

import pandas as pd
import numpy as np

In [70]:
# Reading the dataset

df = pd.read_csv('Churn_Modelling.csv')

In [71]:
# Visualizing 1st 5 data

df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [72]:
# Checking for data types

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [73]:
# Checking for null values

df.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [74]:
# Checking for state value count

df['Surname'].value_counts()
df['Geography'].value_counts()
df['Gender'].value_counts()

Male      5457
Female    4543
Name: Gender, dtype: int64

In [75]:
from sklearn.preprocessing import LabelEncoder

In [76]:
# Initializing encoder

le = LabelEncoder()

In [77]:
# Transforming values

df['Surname'] = le.fit_transform(df['Surname'])
df['Geography'] = le.fit_transform(df['Geography'])
df['Gender'] = le.fit_transform(df['Gender'])



In [78]:
df.head()

RowNumber  CustomerId  Surname  CreditScore  Geography  Gender  Age  \
0          1    15634602     1115          619          0       0   42   
1          2    15647311     1177          608          2       0   41   
2          3    15619304     2040          502          0       0   42   
3          4    15701354      289          699          0       0   39   
4          5    15737888     1822          850          2       0   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [79]:
# Split data (independent & dependent variables)

x = df.iloc[:,0:4].values
y = df.iloc[:,4:5].values

In [80]:
x

array([[       1, 15634602,     1115,      619],
       [       2, 15647311,     1177,      608],
       [       3, 15619304,     2040,      502],
       ...,
       [    9998, 15584532,     1570,      709],
       [    9999, 15682355,     2345,      772],
       [   10000, 15628319,     2751,      792]])

In [81]:
y

array([[0],
       [2],
       [0],
       ...,
       [0],
       [1],
       [0]])

In [82]:
from sklearn.model_selection import train_test_split

In [83]:
# Split data (train & test data)

xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.3,random_state=0)

In [84]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [85]:
# Creating skeleton ANN model

regressor = Sequential()
regressor.add(Dense(4, activation='relu')) # Input
regressor.add(Dense(12, activation='relu')) # 1st hid. layer
regressor.add(Dense(8, activation='relu')) # 2nd hid. layer
regressor.add(Dense(9, activation='relu')) # 3rd hid. layer
regressor.add(Dense(1,activation='linear')) # output layer

In [86]:
# Passing optimizers to the model

regressor.compile(optimizer='adam',loss='mse',metrics=['mse'])

In [ ]:
# Training the model

regressor.fit(xtrain,ytrain,batch_size=10,epochs=300)

Epoch 1/300
700/700 [==============================] - 2s 2ms/step - loss: 1653788.1250 - mse: 1653788.1250
Epoch 2/300
700/700 [==============================] - 2s 2ms/step - loss: 1.5947 - mse: 1.5947
Epoch 3/300
700/700 [==============================] - 1s 2ms/step - loss: 2.3671 - mse: 2.3671
Epoch 4/300
700/700 [==============================] - 1s 2ms/step - loss: 12390.0576 - mse: 12390.0576
Epoch 5/300
700/700 [==============================] - 2s 2ms/step - loss: 73012.6484 - mse: 73012.6484
Epoch 6/300
700/700 [==============================] - 1s 2ms/step - loss: 50110.1484 - mse: 50110.1484
Epoch 7/300
700/700 [==============================] - 1s 2ms/step - loss: 41355.0898 - mse: 41355.0898
Epoch 8/300
700/700 [==============================] - 2s 2ms/step - loss: 29577.1367 - mse: 29577.1367
Epoch 9/300
700/700 [==============================] - 2s 2ms/step - loss: 17027.5742 - mse: 17027.5742
Epoch 10/300
700/700 [==============================] - 2s 2ms/step - loss: 

In [39]:
# Predicting the test data

ypred = regressor.predict(xtest)

In [40]:
ypred

array([[0.7372975],
       [0.7372975],
       [0.7372975],
       ...,
       [0.7372975],
       [0.7372975],
       [0.7372975]], dtype=float32)

In [41]:
ytest

array([[1],
       [0],
       [2],
       ...,
       [0],
       [0],
       [1]])

In [42]:
# Comparing actual ytest values with predicted values

pd.DataFrame({'Actual values':ytest.flatten(),
              'Predicted values':ypred.flatten()})

Actual values  Predicted values
0                 1          0.737297
1                 0          0.737297
2                 2          0.737297
3                 0          0.737297
4                 1          0.737297
...             ...               ...
2995              2          0.737297
2996              0          0.737297
2997              0          0.737297
2998              0          0.737297
2999              1          0.737297

[3000 rows x 2 columns]

In [43]:
from sklearn.metrics import r2_score

In [44]:
# checking accuracy

r2_score(ytest,ypred)*100

-42.53737979456793

In [45]:
regressor.predict([[1234543.34,53343445.34,5645575.3,2]])

array([[0.7372975]], dtype=float32)

In [46]:
# Saving the ANN model weights (it can be used whenever we want... each and every time no need to train model)

regressor.save('regressor.h5')

In [49]:
# Reading the dataset

data = pd.read_csv('data.csv')

In [50]:
# Visualizing 1st 5 data

# output column is diagnosis (M = malignant, B = benign)

data.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [51]:
# Checking for data types

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [52]:
# Checking for null values

data.isnull().sum()

id                           0
diagnosis                    0
radius_mean                  0
texture_mean                 0
perimeter_mean               0
area_mean                    0
smoothness_mean              0
compactness_mean             0
concavity_mean               0
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
smoothness_worst             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst               0
fractal_dimension_worst      0
Unnamed:

In [53]:
# Drop unwanted columns

data.drop(['Unnamed: 32','id'],axis=1,inplace=True)

In [54]:
data.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [55]:
# Split data (independent & dependent variables)

x = data.drop(['diagnosis'],axis=1)
y = data['diagnosis']

In [56]:
# Transforming values

le2 = LabelEncoder()
y = le2.fit_transform(data['diagnosis'])

In [57]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1,

In [58]:
# Split data (train & test data)

xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.3,random_state=0)

In [59]:
xtrain.shape

(398, 30)

In [60]:
# Creating skeleton ANN model

classification = Sequential()
classification.add(Dense(30, activation='relu')) # Input
classification.add(Dense(128, activation='relu')) # 1st hid. layer
classification.add(Dense(64, activation='relu')) # 2nd hid. layer
classification.add(Dense(32, activation='relu')) # 3rd hid. layer
classification.add(Dense(1,activation='sigmoid')) # output layer

In [61]:
# Passing optimizers to the model

classification.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [62]:
# Training the model

classification.fit(xtrain,ytrain,batch_size=10,epochs=300)

Epoch 1/300
40/40 [==============================] - 1s 3ms/step - loss: 2.4077 - accuracy: 0.7387
Epoch 2/300
40/40 [==============================] - 0s 3ms/step - loss: 0.7637 - accuracy: 0.8367
Epoch 3/300
40/40 [==============================] - 0s 3ms/step - loss: 0.7397 - accuracy: 0.8518
Epoch 4/300
40/40 [==============================] - 0s 3ms/step - loss: 0.5872 - accuracy: 0.8970
Epoch 5/300
40/40 [==============================] - 0s 3ms/step - loss: 0.9219 - accuracy: 0.8518
Epoch 6/300
40/40 [==============================] - 0s 3ms/step - loss: 0.6379 - accuracy: 0.8719
Epoch 7/300
40/40 [==============================] - 0s 3ms/step - loss: 0.6250 - accuracy: 0.8744
Epoch 8/300
40/40 [==============================] - 0s 3ms/step - loss: 0.5870 - accuracy: 0.8894
Epoch 9/300
40/40 [==============================] - 0s 3ms/step - loss: 0.8477 - accuracy: 0.8593
Epoch 10/300
40/40 [==============================] - 0s 3ms/step - loss: 0.4228 - accuracy: 0.9020
Epoch 11/

In [63]:
# Predicting the test data

ypred = classification.predict(xtest)

In [64]:
ypred

array([[9.36031222e-01],
       [6.14481920e-04],
       [2.62126327e-04],
       [1.98173910e-01],
       [5.35808722e-05],
       [2.34384493e-06],
       [1.16017866e-07],
       [7.52327821e-07],
       [1.24058675e-03],
       [1.03051880e-10],
       [6.62604049e-02],
       [7.67101720e-02],
       [1.80741857e-08],
       [5.23502171e-01],
       [4.52224128e-02],
       [8.88700008e-01],
       [9.97449519e-08],
       [9.99930024e-01],
       [9.69186902e-01],
       [9.99998569e-01],
       [9.99805987e-01],
       [4.88721818e-01],
       [4.31867171e-04],
       [4.84283024e-04],
       [5.04839957e-01],
       [8.14975519e-03],
       [2.27901055e-05],
       [2.43237261e-02],
       [6.75459101e-04],
       [9.99988556e-01],
       [2.69223783e-05],
       [9.99850392e-01],
       [4.18243371e-02],
       [9.58100855e-01],
       [2.41514968e-08],
       [9.96138752e-01],
       [5.03720045e-02],
       [9.96488571e-01],
       [1.51674938e-03],
       [9.58698511e-01],


In [65]:
np.round(ypred.flatten()).astype('int')

array([1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0])

In [66]:
# Comparing actual ytest values with predicted values

pd.DataFrame({'Actual values':ytest.flatten(),
              'Predicted values':np.round(ypred.flatten()).astype('int')})

Actual values  Predicted values
0                1                 1
1                0                 0
2                0                 0
3                0                 0
4                0                 0
..             ...               ...
166              1                 1
167              1                 1
168              0                 0
169              0                 0
170              0                 0

[171 rows x 2 columns]

In [68]:
# Saving the ANN model weights (it can be used whenever we want... each and every time no need to train model)

classification.save('classification.h5')